CREATE TABLE IF NOT EXISTS products(
    id INTEGER PRIMARY KEY,
    name VARCHAR(256) UNIQUE NOT NULL,
    price FLOAT NOT NULL
);
CREATE TABLE IF NOT EXISTS categories(
    name VARCHAR(256) UNIQUE PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS productCategory(
    id INTEGER PRIMARY KEY,
    prod VARCHAR(256) NOT NULL,
    category VARCHAR(256) NOT NULL
);
CREATE TABLE IF NOT EXISTS orders(
    id INTEGER PRIMARY KEY,
    price FLOAT NOT NULL,
    status VARCHAR(256) NOT NULL,
    created VARCHAR(256) NOT NULL,
    owner VARCHAR(256) NOT NULL
);
CREATE TABLE IF NOT EXISTS orderPro(
    id INTEGER PRIMARY KEY,
    orderId INTEGER FOREIGN KEY REFERENCES orders(id),
    product VARCHAR(256) FOREIGN KEY REFERENCES products(name),
    quantity INTEGER NOT NULL
);
